// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eqogtjjjzedmafitnqoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxb2d0ampqemVkbWFmaXRucW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MzkyMTYsImV4cCI6MjA3MjMxNTIxNn0.BD8ok7U9ItllL6rkcXymki5KNQdiHkJGvcsmzgHYqWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
